title: Akash Hingu
logo: /assets/images/linkedin_circle_smaller1.png
remote_theme: pages-themes/minimal@v0.2.0
description: Experienced data analytics professional for seven years striving to leverage expertise in data analysis, business intelligence, and data visualization to drive business growth.